# This compose file integrates LedFx with BalenaSound
# It must be built using `balena push` and pushed onto a device running Balena OS
# If you find a way to remove this from Balena's ecosystem, let me know, but all of Balena's base images are compiled for amd64 and (presumably) use QEMU to emulate them
# This makes it extremely difficult to deploy on a Pi without Balena, but you might be able to get it working on an x86 system. 

version: '2'

volumes:
  spotifycache:
  ledfx:

services:
  ledfx:
    image: shirom/ledfx:dev
    container_name: ledfx
    environment: 
      - HOST=multiroom-server
    ports:
      - 80:8888
    volumes:
      - ledfx:/root/.ledfx

  # Core services
  audio:
    build: ./core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317

  sound-supervisor:
    build: ./core/sound-supervisor
    network_mode: host
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1

  multiroom-server:
    build: ./core/multiroom/server
    restart: on-failure
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780

  multiroom-client:
    build: ./core/multiroom/client
    restart: on-failure

  # Plugins
  bluetooth:
    build: ./plugins/bluetooth
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1

  airplay:
    build: ./plugins/airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

  spotify:
    build: ./plugins/spotify
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify

  upnp:
    build: ./plugins/upnp
    restart: on-failure
    network_mode: host
    ports:
      - 49494:49494
